name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Copy Secrets
      run: cp /home/office/main_secrets/appsettings.json ./daemon-console/appsettings.json && cp /home/office/main_secrets/cs.txt ./daemon-console/cs.txt
    - name: Clean Solution
      if: success()
      run: dotnet clean --configuration Release
    - name: Restore dependencies
      if: success()
      run: dotnet restore --verbosity detailed
    - name: Build
      if: success()
    # Indien dotnet publish niet werkt dan moet deze stap vervangen worden met 'dotnet build --no-restore'
    # De stap dotnet publish -c Release zal dan moeten verplaatst worden naar 'Run Docker'
      run: dotnet publish -c Release
    - name: Test
      if: success()
      run: dotnet test --no-build --verbosity normal
      
    # Deze stap gaat enkel door wanneer de testen een succes zijn!    
    - name: Run Docker
      if: success()
      run: bash startup.sh
